- name: user creation
  hosts: local
  connection: local
  tasks:
   - name: check user exit or not
     ansible.builtin.command: id roboshop
     register: output
     ignore_errors: true

   - name: user creation
     become: yes
     ansible.builtin.command: useradd roboshop
     when: output.rc !=0  

   - name: user alredy exist
     ansible.builtin.debug:
      msg: "user alredy exist"
     when: output.rc== 0    